# go-reminders minimal container definition

# Start from scratch
FROM scratch
MAINTAINER Luis M. Valerio <lvaleriocasti@vmware.com>

# Add the microservice
ADD data-manager /data-manager

# Add the content (html and templates)
ADD html /html
